-- matchon 초기 스키마 (PostgreSQL / Supabase)
-- 축구·풋살 동호회 출석 관리 보조 서비스

-- updated_at 자동 갱신용 트리거 함수 (Postgres 는 MySQL 의 ON UPDATE 가 없음)
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- USERS : 카카오 로그인 사용자
-- ============================================================
CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_id      VARCHAR(64)  NOT NULL,
    nickname      VARCHAR(20)  NOT NULL,
    position      VARCHAR(8),
    profile_image VARCHAR(255),
    setup_done    BOOLEAN      NOT NULL DEFAULT false,
    created_at    TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_kakao_id UNIQUE (kakao_id)
);
CREATE TRIGGER trg_users_updated BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- TEAM : 동호회(팀)
-- ============================================================
CREATE TABLE team (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(40)  NOT NULL,
    description   VARCHAR(255),
    invite_code   VARCHAR(12)  NOT NULL,
    emblem        VARCHAR(255),
    min_attendees INT          NOT NULL DEFAULT 0,
    owner_id      BIGINT       NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_team_invite_code UNIQUE (invite_code),
    CONSTRAINT fk_team_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);
CREATE INDEX idx_team_owner ON team(owner_id);

-- ============================================================
-- TEAM_MEMBER : 팀 가입 관계 + 권한
-- ============================================================
CREATE TABLE team_member (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id     BIGINT      NOT NULL,
    user_id     BIGINT      NOT NULL,
    role        VARCHAR(12) NOT NULL DEFAULT 'MEMBER',
    back_number INT,
    joined_at   TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT uq_team_member UNIQUE (team_id, user_id),
    CONSTRAINT fk_tm_team FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE,
    CONSTRAINT fk_tm_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_tm_user ON team_member(user_id);
CREATE INDEX idx_tm_team_role ON team_member(team_id, role);

-- ============================================================
-- MATCH_SCHEDULE : 경기 일정
-- ============================================================
CREATE TABLE match_schedule (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id     BIGINT       NOT NULL,
    title       VARCHAR(60)  NOT NULL,
    match_date  DATE         NOT NULL,
    start_time  TIME         NOT NULL,
    end_time    TIME,
    place       VARCHAR(120),
    fee         INT          NOT NULL DEFAULT 0,
    memo        VARCHAR(500),
    created_by  BIGINT       NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT fk_ms_team FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE,
    CONSTRAINT fk_ms_creator FOREIGN KEY (created_by) REFERENCES users(id)
);
CREATE INDEX idx_ms_team_date ON match_schedule(team_id, match_date);
CREATE INDEX idx_ms_date ON match_schedule(match_date);

-- ============================================================
-- ATTENDANCE : 참석 여부 + 회비 납부
-- ============================================================
CREATE TABLE attendance (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT      NOT NULL,
    user_id     BIGINT      NOT NULL,
    status      VARCHAR(8)  NOT NULL DEFAULT 'PENDING',
    paid        BOOLEAN     NOT NULL DEFAULT false,
    updated_at  TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT uq_attendance UNIQUE (schedule_id, user_id),
    CONSTRAINT fk_att_schedule FOREIGN KEY (schedule_id) REFERENCES match_schedule(id) ON DELETE CASCADE,
    CONSTRAINT fk_att_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_att_user ON attendance(user_id);
CREATE INDEX idx_att_schedule_status ON attendance(schedule_id, status);
CREATE TRIGGER trg_attendance_updated BEFORE UPDATE ON attendance
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- COMMENT : 일정 댓글
-- ============================================================
CREATE TABLE comment (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT       NOT NULL,
    user_id     BIGINT       NOT NULL,
    content     VARCHAR(300) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT fk_cmt_schedule FOREIGN KEY (schedule_id) REFERENCES match_schedule(id) ON DELETE CASCADE,
    CONSTRAINT fk_cmt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_cmt_schedule ON comment(schedule_id, created_at);

-- ============================================================
-- NOTIFICATION : 발송 알림 이력
-- ============================================================
CREATE TABLE notification (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id     BIGINT       NOT NULL,
    schedule_id BIGINT,
    type        VARCHAR(20)  NOT NULL,
    message     VARCHAR(500) NOT NULL,
    sent        BOOLEAN      NOT NULL DEFAULT false,
    sent_at     TIMESTAMP,
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT fk_noti_team FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE,
    CONSTRAINT fk_noti_schedule FOREIGN KEY (schedule_id) REFERENCES match_schedule(id) ON DELETE CASCADE
);
CREATE INDEX idx_noti_schedule_type ON notification(schedule_id, type);
CREATE INDEX idx_noti_team ON notification(team_id);
