-- 팀 매칭(친선경기 모집) 기능
-- 한 팀이 매칭을 올리면 다른 팀 팀장/운영진이 신청

CREATE TABLE match_post (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_team_id BIGINT       NOT NULL,
    host_user_id BIGINT       NOT NULL,
    level        VARCHAR(8)   NOT NULL,                 -- HIGH(상)/MID(중)/LOW(하)
    headcount    INT          NOT NULL DEFAULT 0,       -- 모집 인원(팀 인원)
    region       VARCHAR(60),                           -- 지역 (예: 서울 송파구)
    place_name   VARCHAR(120),                          -- 장소명
    lat          DOUBLE PRECISION,                      -- 위도
    lng          DOUBLE PRECISION,                      -- 경도
    match_date   DATE,
    start_time   TIME,
    memo         VARCHAR(500),
    status       VARCHAR(10)  NOT NULL DEFAULT 'OPEN',  -- OPEN/MATCHED/CLOSED
    created_at   TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT fk_mp_team FOREIGN KEY (host_team_id) REFERENCES team(id) ON DELETE CASCADE,
    CONSTRAINT fk_mp_user FOREIGN KEY (host_user_id) REFERENCES users(id)
);
CREATE INDEX idx_mp_status_date ON match_post(status, match_date);
CREATE INDEX idx_mp_region ON match_post(region);

CREATE TABLE match_application (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_post_id     BIGINT       NOT NULL,
    applicant_team_id BIGINT       NOT NULL,
    applicant_user_id BIGINT       NOT NULL,
    message           VARCHAR(300),
    status            VARCHAR(10)  NOT NULL DEFAULT 'PENDING',  -- PENDING/ACCEPTED/REJECTED
    created_at        TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_application UNIQUE (match_post_id, applicant_team_id),
    CONSTRAINT fk_ma_post FOREIGN KEY (match_post_id) REFERENCES match_post(id) ON DELETE CASCADE,
    CONSTRAINT fk_ma_team FOREIGN KEY (applicant_team_id) REFERENCES team(id) ON DELETE CASCADE,
    CONSTRAINT fk_ma_user FOREIGN KEY (applicant_user_id) REFERENCES users(id)
);
CREATE INDEX idx_ma_post ON match_application(match_post_id);
CREATE INDEX idx_ma_team ON match_application(applicant_team_id);
