-- 용병(게스트) — 팀원이 아닌 외부 참석 인원 수동 추가
CREATE TABLE match_guest (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT      NOT NULL,
    name        VARCHAR(40) NOT NULL,
    headcount   INT         NOT NULL DEFAULT 1,
    added_by    BIGINT      NOT NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT fk_guest_schedule FOREIGN KEY (schedule_id) REFERENCES match_schedule(id) ON DELETE CASCADE,
    CONSTRAINT fk_guest_user FOREIGN KEY (added_by) REFERENCES users(id)
);
CREATE INDEX idx_guest_schedule ON match_guest(schedule_id);
