-- 팀 가입 신청 (팀장 승인 방식)
CREATE TABLE join_request (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id    BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    status     VARCHAR(10) NOT NULL DEFAULT 'PENDING',  -- PENDING/ACCEPTED/REJECTED
    created_at TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT uq_join_req UNIQUE (team_id, user_id),
    CONSTRAINT fk_jr_team FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE,
    CONSTRAINT fk_jr_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_jr_team ON join_request(team_id, status);
CREATE INDEX idx_jr_user ON join_request(user_id, status);
